title: Slate theme
description: Slate is a theme for GitHub Pages.
show_downloads: true
theme: jekyll-theme-slate
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-seo-tag
